---
language: node_js
node_js:
- 0.1
env:
  global:
  - secure: ! 'FnBcXozTt3WZNLevBALTtL1JT6KPFafSaeEvuXK50V1zbUBcIIBFUneld/BS\nDUPC3TFzYYBHaeBA+v786OoQmdFM+bbEF7xaklXDR7I6p12Cp+O4pY+BUzN2\naqBENb9I4e1uI1MVyXnlftaknseJ87DGAMHXWz9iS90f5MlrsOA='
  - secure: ! 'EXuDF+EpHa5ih5uzBQeTELfdgoQ+Vz1zO1N4+RWlgiqEr/Bar6gK+i8P1JwJ\nz3TTYSnjrBLE/W0gIitPRa8wWhAuzXxCi+YKIVGHe1EO14TTVpEJoIHT/ndl\nBnmFG2sPHyCqK/3kP5By5NWwJJW1wCgPu5XBRUymSIUo05QucB4='
